version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: celerbuild-example-php
    container_name: celerbuild-example-php
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - .:/var/www/celerbuild-example-php
    networks:
      - celerbuild

networks:
  celerbuild:
    driver: bridge
