version: '3.8'

services:
  app:
    image: ${REGISTRY_URL}/library/celerbuild-example-php:${IMAGE_TAG}
    container_name: celerbuild-example-php
    restart: unless-stopped
    env_file:
      - .env.docker
    networks:
      - celerbuild_network

networks:
  celerbuild_network:
    name: celerbuild_network
    driver: bridge